# Generated by Django 3.2.8 on 2021-11-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insert_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='xxx',
            field=models.CharField(default=123, max_length=78),
            preserve_default=False,
        ),
    ]
